MOV CL,0AH  ;COUNT
MOV BL,00H  ;POSITIVE
MOV DL,00H  ;NEGATIVE
LEA SI,[1000H] ;LOAD EFFECTIVE ADDRESS SI-16BITS

L1:MOV AL,[SI]
SHL AL,01     ;SHIFT ARITHMETIC LEFT
JNC L2        ;JUMP IF NO CARRY
INC DL        ;IF NO CF=1 DL++
JMP L3
L2:INC BL
L3:INC SI
DEC CL 
JNZ L1
MOV [100AH],BL
MOV [100BH],DL
HLT
